version: '3.8'

services:
  stereo-vision-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stereo-vision-api
    ports:
      - "8000:8000"
    volumes:
      # Mount calibration (read-only)
      - ./calibration:/app/calibration:ro
      # Mount outputs (read-write)
      - ./outputs:/app/outputs
      # Optional: Mount KITTI data if available
      - ./data:/app/data:ro
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

networks:
  default:
    name: stereo-vision-network
